---
# Role check tasks

- name: check if mysql jdbc connector is installed
  stat:
    path: "{{ mysql_jdbc_connector_jar_path }}"
  register: mysql_jdbc_connector_jar_check_result
  vars:
    distribution: "{{ ansible_facts.distribution | lower }}"
  tags:
    - role::mysql_jdbc_connector
    - role::mysql_jdbc_connector::check
