---
# Role cleanup tasks

- block:
    - include_tasks: artifact.yml
      vars:
        mysql_jdbc_connector_artifact_state: absent
  tags:
    - role::mysql_jdbc_connector
    - role::mysql_jdbc_connector::cleanup
