---
# Role download tasks

- name: download mysql jdbc connector artifact
  include_role:
    name: amtega.artifact
  vars:
    override:
      download: "{{ not mysql_jdbc_connector_jar_check_result.stat.exists }}"
    artifact: >-
      {{ mysql_jdbc_connector_artifact | combine(override) }}
  when:
    - mysql_jdbc_connector_state == "present"
  tags:
    - role::mysql_jdbc_connector
    - role::mysql_jdbc_connector::download
