---
# Role download tasks

- name: download mysql jdbc connector artifact
  include_role:
    name: amtega.artifact
  vars:
    artifact: "{{ mysql_jdbc_connector_artifact }}"
  when:
    - mysql_jdbc_connector_state == "present"
    - not mysql_jdbc_connector_jar_check_result.stat.exists
  tags:
    - role::mysql_jdbc_connector
    - role::mysql_jdbc_connector::download
