---
# Role facts tasks

- block:
    - name: Setup fact with mysql jdbc connector path
      set_fact:
        mysql_jdbc_connector_jar_path: "{{ mysql_jdbc_connector_jar_path }}"

    - name: Create local facts directory
      file:
        path: /etc/ansible/facts.d
        state: directory

    - name: Setup mysql jdbc connector local fact
      template:
        src: connector.fact.j2
        dest: /etc/ansible/facts.d/mysql_jdbc_connector.fact
        mode: 0640
  tags:
    - role::mysql_jdbc_connector::facts
