---

- name: Setup ansible local facts
  block:
    - name: Setup fact with mysql jdbc connector path
      ansible.builtin.set_fact:
        mysql_jdbc_connector_jar_path: "{{ mysql_jdbc_connector_jar_path }}"

    - name: Create local facts directory
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: directory
        mode: 0755

    - name: Setup mysql jdbc connector local fact
      ansible.builtin.template:
        src: connector.fact.j2
        dest: /etc/ansible/facts.d/mysql_jdbc_connector.fact
        mode: 0640
  tags:
    - role::mysql_jdbc_connector::facts
