---
# Role install tasks

- block:
    - include_tasks: artifact.yml
      vars:
        mysql_jdbc_connector_artifact_state: present

    - name: Create mysql jdbc connector destination directory
      file:
        path: "{{ mysql_jdbc_connector_dir }}"
        state: directory

    - name: Install mysql jdbc connector
      copy:
        src: >-
          {{ mysql_jdbc_connector_unarchive_dir
             + "/"
             + mysql_jdbc_connector_jar_filename }}
        dest: "{{ mysql_jdbc_connector_dir }}"
        remote_src: yes
  tags:
    - role::mysql_jdbc_connector
    - role::mysql_jdbc_connector::install
