---
# Gather latest version tasks

- block:
    - name: Check internet connection availability
      wait_for:
        host: "{{ host }}"
        port: "{{ (port is none) | ternary(80, port) }}"
        connect_timeout: 1
        timeout: 1
      vars:
        host: "{{ mysql_jdbc_connector_site | urlsplit('hostname') }}"
        port: "{{ mysql_jdbc_connector_site | urlsplit('port') }}"
      register: mysql_jdbc_connector_check_internet_result

    - name: Setup mysql jdbc connector latest version
      when: mysql_jdbc_connector_version == "latest"
      set_fact:
        mysql_jdbc_connector_latest_version: >-
          {{ lookup("url", mysql_jdbc_connector_site, wantlist=True)
             | select("search", "<h1>Connector/J *.* *</h1>")
             | first
             | regex_replace(".*<h1>Connector/J (.*)</h1>.*", "\1")
             | trim }}
  when: >-
    mysql_jdbc_connector_artifact.host
    == mysql_jdbc_connector_site | urlsplit('hostname')
  tags:
    - role::mysql_jdbc_connector
