---

- name: Setup mysql jdbc connector
  block:
    - ansible.builtin.include_tasks: latest.yml

    - ansible.builtin.include_tasks: search.yml

    - ansible.builtin.include_tasks: install.yml
      when:
        - mysql_jdbc_connector_state == "present"
        - mysql_jdbc_connector_install_required | bool

    - ansible.builtin.include_tasks: uninstall.yml
      when: >-
        mysql_jdbc_connector_state == "absent"
        or (mysql_jdbc_connector_state == "present"
            and mysql_jdbc_connector_install_required | bool)

    - ansible.builtin.include_tasks: cleanup.yml
      tags:
        - role::mysql_jdbc_connector::cleanup

    - ansible.builtin.include_tasks: facts.yml
      tags:
        - role::mysql_jdbc_connector::facts
  tags:
    - role::mysql_jdbc_connector
