---

- name: Uninstall mysql jdbc connector
  ansible.builtin.file:
    path: "{{ mysql_jdbc_connector_item }}"
    state: absent
  loop: >-
    {{ mysql_jdbc_connector_search_result.files
       | map(attribute="path")
       | list }}
  loop_control:
    loop_var: mysql_jdbc_connector_item
  tags:
    - role::mysql_jdbc_connector
    - role::mysql_jdbc_connector::uninstall
