---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Load role variables
      include_vars: ../../vars/main.yml

    - name: Check mysql connector install
      stat:
        path: "{{ mysql_jdbc_connector_jar_path }}"
      register: check_connector_result

    - name: Check that mysql connector was installed
      assert:
        that: check_connector_result.stat.exists
